Repository mogland/core, pull requests merged in 2022-10, with the labels that each got.

#393 perf(app): define the microservice startup port
  apps/core/src/modules/category/category.module.ts
  apps/core/src/modules/page/page.module.ts
  apps/core/src/modules/post/post.module.ts
  apps/core/src/modules/user/user.module.ts
  apps/page-service/src/main.ts
  apps/page-service/src/page-service.module.ts
  apps/page-service/src/page-service.service.ts
  apps/user-service/src/main.ts
  libs/database/src/database.module.ts
  shared/constants/services.constant.ts
Labels: improve-performance

#394 feat(user-service): get master info directly
  apps/core/src/modules/user/user.controller.ts
  apps/user-service/src/user-service.controller.ts
  apps/user-service/src/user-service.service.ts
  apps/user-service/src/user.model.ts
  shared/constants/event.constant.ts
Labels: enhancement, module/user, improve-performance

#395 docs(contributing): how to contribute to core (#395) [skip ci]
  CONTRIBUTING.md
Labels: documentation

#397 fix: build apps return an unexpected type error
  apps/core/src/app.controller.ts
  apps/core/src/bootstrap.ts
  global.d.ts
  libs/database/src/database.provider.ts
  libs/helper/src/helper.jwt.service.ts
  shared/common/decorator/api-controller.decorator.ts
  shared/common/decorator/openapi.decorator.ts
  shared/common/filters/any-exception.filter.ts
  shared/global/index.global.ts
Labels: bug-fix

#398 feat: ncc bundle
  package.json
Labels: enhancement

#399 perf(nest): use `tsc` to build and make tsconfig file correctly
  global.d.ts
  nest-cli.json
  shared/global/index.global.ts
Labels: improve-performance, bug-fix

#400 ci: build and pull request bundle test ci
  .github/workflows/build.yml
  .github/workflows/pull.yml
  apps/core/tsconfig.app.json
  apps/page-service/tsconfig.app.json
  apps/user-service/tsconfig.app.json
  nest-cli.json
  package.json
  scripts/workflow/test-server.sh
Labels: enhancement, ci-failed

#406 ci(pull-approve): auto create approve review for owner (#406) [skip ci]
  .github/workflows/pull-approve.yml
Labels: ci-passed

#405 style: lint code with using prettier and eslint
  .eslintrc.js
  .github/FUNDING(pre).yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feat_report.md
  .github/renovate.json
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pull.yml
  .github/workflows/release.yml
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
  apps/core/tsconfig.app.json
  apps/user-service/tsconfig.app.json
  libs/cache/src/cache.config.service.ts
  libs/cache/src/cache.module.ts
  libs/cache/src/cache.service.ts
  libs/database/src/model.transformer.ts
  libs/helper/src/helper.http.service.ts
  nest-cli.json
  pnpm-lock.yaml
  readme.md
  shared/constants/cache.constant.ts
  shared/constants/meta.constant.ts
  shared/constants/system.constant.ts
  shared/dto/file.dto.ts
  shared/dto/id.dto.ts
  shared/dto/pager.dto.ts
  shared/model/image.model.ts
  shared/transformers/model.transformer.ts
  shared/transformers/paginate.transformer.ts
  shared/utils/environment.util.ts
  shared/utils/index.ts
  shared/utils/redis.util.ts
  shared/utils/rss-parser.util.ts
  shared/utils/safe-eval.util.ts
  shared/utils/time.util.ts
  shared/utils/validator/simpleValidatorFactory.ts
  tsconfig.json
Labels: ci-passed

#408 ci(pull-approve): improve ci approve comment body
  .github/workflows/pull.yml
Labels: ci-passed

#440 docs(readme): re-design readme page (#440) [skip ci]
  readme.md
Labels: documentation, ci-passed
