Repository mogland/core, pull requests merged in 2023-04, with the labels that each got.

#720 fix(themes): active multi-themes
  apps/core/src/bootstrap.ts
  apps/core/src/modules/themes/themes.controller.ts
  apps/themes-service/src/themes-service.service.ts
Labels: module/themes, ci-passed

#721 perf(themes): track all themes config changes
  apps/themes-service/src/themes-service.service.ts
Labels: enhancement, module/themes, ci-passed

#749 fix(friends-service): crash when analysing wrong feed
  apps/core/src/modules/themes/themes.controller.ts
  apps/friends-service/src/friends-service.service.ts
Labels: module/links, bug-fix

#751 fix(friends-service): wrong comment details api
  apps/comments-service/src/comments-service.controller.ts
  apps/comments-service/src/comments-service.service.ts
  apps/core/src/modules/comments/comments.controller.ts
  shared/constants/event.constant.ts
Labels: bug-fix

#763 fix(dependencies): downgrade pure esm dependencies
  package.json
  pnpm-lock.yaml
Labels: ci-passed, ci-ignore

#762 feat(store-service): assets store service support
  apps/core/src/app.module.ts
  apps/core/src/common/adapt/fastify.adapt.ts
  apps/core/src/modules/store/store.controller.ts
  apps/core/src/modules/store/store.module.ts
  apps/store-service/src/main.ts
  apps/store-service/src/store-service.controller.ts
  apps/store-service/src/store-service.module.ts
  apps/store-service/src/store-service.service.ts
  apps/store-service/tsconfig.app.json
  apps/themes-service/src/themes-service.service.ts
  libs/helper/src/helper.assets.service.ts
  mog-core.code-workspace
  nest-cli.json
  package.json
  pnpm-lock.yaml
  shared/common/decorator/http.decorator.ts
  shared/constants/event.constant.ts
  shared/constants/path.constant.ts
  shared/constants/services.constant.ts
  shared/exceptions/internal-server-error-rpc-exception.ts
  shared/global/index.global.ts
Labels: enhancement, ci-passed

#766 feat(core): json migrate module
  apps/comments-service/src/comments-service.controller.ts
  apps/comments-service/src/comments-service.service.ts
  apps/core/src/app.module.ts
  apps/core/src/modules/migrate/migrate.controller.ts
  apps/core/src/modules/migrate/migrate.interface.ts
  apps/core/src/modules/migrate/migrate.module.ts
  apps/core/src/modules/migrate/migrate.service.ts
  apps/friends-service/src/friends-service.controller.ts
  apps/friends-service/src/friends-service.service.ts
  apps/page-service/src/page-service.controller.ts
  apps/page-service/src/page-service.service.ts
  apps/user-service/src/user-service.service.ts
Labels: enhancement, ci-passed
