Repository mogland/core, pull requests merged in 2023-01, with the labels that each got.

#559 perf(microservice): transport req to microservice
  apps/core/src/modules/category/category.controller.ts
  apps/core/src/modules/page/page.controller.ts
  apps/core/src/modules/post/post.controller.ts
  apps/core/src/modules/user/user.controller.ts
  shared/microservice.transporter.ts
Labels: enhancement, ci-passed

#558 feat(comments): standalone comments microservice
  apps/comments-service/src/comments-service.controller.ts
  apps/comments-service/src/comments-service.module.ts
  apps/comments-service/src/comments-service.service.ts
  apps/comments-service/src/comments.model.ts
  apps/comments-service/src/main.ts
  apps/comments-service/tsconfig.app.json
  apps/core/src/modules/comments/comments.basic.service.ts
  apps/core/src/modules/comments/comments.controller.ts
  apps/core/src/modules/comments/comments.model.basic.ts
  apps/core/src/modules/comments/comments.module.ts
  apps/user-service/src/user-service.service.ts
  libs/database/src/database.module.ts
  nest-cli.json
  package.json
  shared/constants/echo.constant.ts
  shared/constants/event.constant.ts
  tsconfig.json
Labels: enhancement, module/comments, feature-request

#565 feat(apps): fully friends microservice
  apps/core/src/app.module.ts
  apps/core/src/modules/friends/friends.basic.model.ts
  apps/core/src/modules/friends/friends.basic.service.ts
  apps/core/src/modules/friends/friends.controller.ts
  apps/core/src/modules/friends/friends.module.ts
  apps/friends-service/src/friends-service.controller.ts
  apps/friends-service/src/friends-service.module.ts
  apps/friends-service/src/friends-service.service.ts
  apps/friends-service/src/friends.model.ts
  apps/friends-service/src/main.ts
  apps/friends-service/tsconfig.app.json
  libs/database/src/database.module.ts
  nest-cli.json
  package.json
  pnpm-lock.yaml
  shared/constants/echo.constant.ts
  shared/constants/event.constant.ts
  shared/constants/services.constant.ts
  shared/microservice.transporter.ts
  shared/utils/rss-parser.util.ts
Labels: enhancement, module/links, ci-passed

#566 refactor(apps): use redis as the transporter instead of tcp
  apps/comments-service/src/main.ts
  apps/core/src/modules/category/category.module.ts
  apps/core/src/modules/comments/comments.module.ts
  apps/core/src/modules/friends/friends.module.ts
  apps/core/src/modules/page/page.module.ts
  apps/core/src/modules/post/post.module.ts
  apps/core/src/modules/user/user.module.ts
  apps/friends-service/src/main.ts
  apps/page-service/src/main.ts
  apps/user-service/src/main.ts
Labels: improve-performance

#570 style: remove unused import
  apps/comments-service/src/main.ts
  apps/core/src/modules/category/category.module.ts
  apps/core/src/modules/comments/comments.module.ts
  apps/core/src/modules/friends/friends.module.ts
  apps/core/src/modules/page/page.module.ts
  apps/core/src/modules/post/post.module.ts
  apps/core/src/modules/user/user.module.ts
  apps/friends-service/src/main.ts
  apps/page-service/src/main.ts
  apps/user-service/src/main.ts
Labels: ci-passed, ci-ignore

#568 feat(apps): events notification service
  apps/comments-service/src/comments-service.controller.ts
  apps/comments-service/src/comments-service.module.ts
  apps/comments-service/src/comments-service.service.ts
  apps/core/src/app.module.ts
  apps/core/src/modules/user/user.controller.ts
  apps/friends-service/src/friends-service.module.ts
  apps/friends-service/src/friends-service.service.ts
  apps/notification-service/src/main.ts
  apps/notification-service/src/notification-service.controller.ts
  apps/notification-service/src/notification-service.module.ts
  apps/notification-service/src/notification-service.service.ts
  apps/notification-service/src/templates/guest.friends.ejs
  apps/notification-service/src/templates/owner.friends.ejs
  apps/notification-service/tsconfig.app.json
  apps/page-service/src/page-service.module.ts
  apps/page-service/src/page-service.service.ts
  apps/page-service/src/post-service.service.ts
  apps/user-service/src/user-service.controller.ts
  apps/user-service/src/user-service.module.ts
  apps/user-service/src/user-service.service.ts
  libs/config/src/config.default.ts
  libs/config/src/config.dto.ts
  libs/config/src/config.interface.ts
  mog-core.code-workspace
  nest-cli.json
  package.json
  shared/common/filters/any-exception.filter.ts
  shared/constants/event.constant.ts
  shared/constants/services.constant.ts
Labels: enhancement, ci-passed, module/notification

#575 fix(page-service): get query props from a wrong key
  apps/page-service/src/page-service.controller.ts
Labels: module/posts, bug-fix, ci-passed, ci-ignore

#585 feat(core): public config module operation apis
  apps/core/src/app.module.ts
  apps/core/src/modules/configs/configs.controller.ts
  apps/core/src/modules/configs/configs.module.ts
  libs/config/src/config.service.ts
Labels: enhancement, module/configs

#592 feat: docker deploy support
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  scripts/workflow/test-docker.sh
Labels: enhancement, ci-passed, ci-ignore

#597 fix(ci): remove db_host
  env.yaml
  scripts/workflow/test-docker.sh
Labels: bug-fix

#600 refactor: the universal transporter register
  apps/comments-service/src/comments-service.module.ts
  apps/core/src/app.module.ts
  apps/core/src/modules/category/category.module.ts
  apps/core/src/modules/comments/comments.module.ts
  apps/core/src/modules/friends/friends.module.ts
  apps/core/src/modules/page/page.module.ts
  apps/core/src/modules/post/post.module.ts
  apps/core/src/modules/user/user.module.ts
  apps/friends-service/src/friends-service.module.ts
  apps/page-service/src/page-service.module.ts
  apps/user-service/src/user-service.module.ts
  shared/constants/transporter.constants.ts
Labels: ci-passed

#603 fix(libs): prototype pollute with patching config
  libs/config/src/config.service.ts
Labels: module/configs, bug-fix, ci-passed

#604 feat(core): built-in console application
  apps/core/src/app.module.ts
  apps/core/src/bootstrap.ts
  apps/core/src/modules/console/console.controller.ts
  apps/core/src/modules/console/console.interface.ts
  apps/core/src/modules/console/console.module.ts
  apps/core/src/modules/console/console.service.ts
  env.yaml
  package.json
  pnpm-lock.yaml
  shared/common/decorator/cookie.decorator.ts
  shared/constants/echo.constant.ts
  shared/types/npm.ts
Labels: enhancement, ci-passed

#606 fix: catch reading nonexistent env file error
  shared/utils/rag-env.ts
Labels: bug-fix

#610 fix(config): unable to validate and store array values
  libs/config/src/config.service.ts
Labels: bug-fix

#612 perf(core): set global prefix exclude for console
  apps/core/src/bootstrap.ts
Labels: bug-fix

#618 perf(page-service): tag searching return data with all fields
  apps/page-service/src/category.service.ts
Labels: enhancement, module/category
