Repository mogland/core, pull requests merged in 2023-05, with the labels that each got.

#772 feat(console): refresh console version cache
  apps/core/src/modules/console/console.controller.ts
  apps/core/src/modules/console/console.service.ts
  env.yaml
  libs/helper/src/helper.http.service.ts
  shared/constants/echo.constant.ts
  shared/constants/others.constant.ts
Labels: ci-passed

#781 fix(themes-service): work failed due to fatal crash bug
  apps/themes-service/src/themes-service.service.ts
Labels: module/themes, bug-fix

#789 fix(configs): array element deduplication
  libs/config/src/config.service.ts
Labels: module/configs, bug-fix

#795 feat(store-service): support rename or move file
  apps/core/src/modules/store/store.controller.ts
  apps/store-service/src/store-service.controller.ts
  apps/store-service/src/store-service.service.ts
  libs/helper/src/helper.assets.service.ts
  shared/constants/event.constant.ts
Labels: enhancement

#796 feat(notification-service): schedule tasks support
  apps/core/src/app.module.ts
  apps/core/src/modules/schedule/schedule.controller.ts
  apps/core/src/modules/schedule/schedule.module.ts
  apps/notification-service/src/notification-schedule.controller.ts
  apps/notification-service/src/notification-schedule.service.ts
  apps/notification-service/src/notification-service.module.ts
  apps/notification-service/src/schedule.enum.ts
  apps/store-service/src/store-service.service.ts
  libs/config/src/config.default.ts
  libs/config/src/config.dto.ts
  libs/config/src/config.interface.ts
  libs/config/src/config.service.ts
  libs/helper/src/helper.assets.service.ts
  package.json
  pnpm-lock.yaml
  shared/constants/event.constant.ts
  shared/utils/toboolean.util.ts
  shared/utils/validator/isCron.ts
Labels: ci-passed, module/notification
