Repository mogland/core, pull requests merged in 2023-02, with the labels that each got.

#607 feat: independent themes system service
  apps/core/src/app.module.ts
  apps/core/src/main.ts
  apps/core/src/modules/themes/themes.controller.ts
  apps/core/src/modules/themes/themes.module.ts
  apps/page-service/src/page-service.controller.ts
  apps/themes-service/src/fastify.adapt.ts
  apps/themes-service/src/main.ts
  apps/themes-service/src/theme.interface.ts
  apps/themes-service/src/themes-render.service.ts
  apps/themes-service/src/themes-service.controller.ts
  apps/themes-service/src/themes-service.module.ts
  apps/themes-service/src/themes-service.service.ts
  apps/themes-service/tsconfig.app.json
  libs/config/src/config.default.ts
  libs/config/src/config.dto.ts
  libs/config/src/config.interface.ts
  libs/config/src/config.module.ts
  libs/helper/src/helper.assets.service.ts
  mog-core.code-workspace
  nest-cli.json
  package.json
  pnpm-lock.yaml
  shared/constants/event.constant.ts
  shared/constants/services.constant.ts
  shared/global/index.global.ts
  shared/utils/i18n.ts
  shared/utils/query-param.ts
  shared/utils/rag-env.ts
Labels: enhancement, module/themes, ci-passed

#641 docs(readme): re-design readme introduction
  .all-contributorsrc
  README.md
Labels: documentation, ci-passed

#663 feat(microservice)!: remove microservice transporter Observable type
  apps/core/src/modules/category/category.controller.ts
  apps/themes-service/src/themes-render.service.ts
  shared/microservice.transporter.ts
Labels: ci-passed

#664 feat(microservice): xRpcException and extend official exception
  apps/comments-service/src/comments-service.service.ts
  apps/friends-service/src/friends-service.service.ts
  apps/page-service/src/category.service.ts
  apps/page-service/src/page-service.controller.ts
  apps/page-service/src/page-service.service.ts
  apps/page-service/src/post-service.service.ts
  apps/user-service/src/user-service.service.ts
  shared/exceptions/bad-request-rpc-exception.ts
  shared/exceptions/forbidden-rpc-exception.ts
  shared/exceptions/not-found-rpc-exception.ts
  shared/exceptions/not-implemented-rpc-exception.ts
  shared/exceptions/rpc-exception.ts
  shared/exceptions/unauthorized-rpc-exception.ts
Labels: ci-passed

#667 feat(microservice): transport custom events
  apps/core/src/app.controller.ts
  apps/core/src/app.module.ts
  apps/core/src/app.service.ts
  env.yaml
  events.yaml
  shared/constants/services.constant.ts
  shared/microservice.transporter.ts
  shared/utils/rag-env.ts
Labels: ci-passed
